name: Basic QA
on: push

jobs:
  basic-qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: |
        go get .
        sudo apt install gcc libgl1-mesa-dev xorg-dev libxkbcommon-dev

    - name: Lint
      run: |
        test -z "$(go fmt)"
        test -z "$(go fmt ./src)"

    - name: Test
      run: go test -v 

    - name: Build
      run: go build -o lckbx -v
      working-directory: ./src

