name: Basic QA
on: pull_request

jobs:
  basic-qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go get .

    - name: Lint
      run:
        - go fmt
        - cd src && go fmt

    - name: Test
      run:
        - cd .. && go test -v ./...

    - name: Build
      run:
        - go build -v ./...

